"""add core tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-16 18:08:06.736195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancer_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancer_requests_email'), 'freelancer_requests', ['email'], unique=True)
    op.create_table('freelancers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancers_email'), 'freelancers', ['email'], unique=True)
    op.create_index(op.f('ix_freelancers_referral_code'), 'freelancers', ['referral_code'], unique=True)
    # NOTE: 'slug' column + ix_freelancers_slug are intentionally NOT created here —
    # the add_freelancer_slug migration (which now runs immediately after this one)
    # adds that column and backfills it for existing rows.
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('architect', 'navigator', 'operator', 'solo', name='userrole_enum', create_constraint=True), server_default='operator', nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('slack_user_id', sa.String(length=64), nullable=True),
    sa.Column('slack_team_id', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_status', sa.String(length=32), server_default='trialing', nullable=False),
    sa.Column('ls_customer_id', sa.String(length=128), nullable=True),
    sa.Column('ls_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('referred_by_code', sa.String(length=32), nullable=True, comment='Referral code of the freelancer who referred this user'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_user_workspace', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_referred_by_code'), 'users', ['referred_by_code'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_workspace_owner', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable label, e.g. Notion Integration'),
    sa.Column('key_hash', sa.String(length=128), nullable=False, comment='SHA-256 hash of the raw API key'),
    sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='First 8 chars of the raw key shown in UI, e.g. sk_live_ab'),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_api_key_creator'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_api_key_workspace'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_workspace_id', 'api_keys', ['workspace_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('bug', 'feedback', 'feature_request', name='feedbacktype_enum', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page_context', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_review', 'resolved', name='feedbackstatus_enum', create_constraint=True), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_feedback_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_status', 'feedback', ['status'], unique=False)
    op.create_index('ix_feedback_type', 'feedback', ['type'], unique=False)
    op.create_index('ix_feedback_user_id', 'feedback', ['user_id'], unique=False)
    op.create_table('onboarding_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slack_connected', sa.Boolean(), nullable=False),
    sa.Column('slack_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_command_sent', sa.Boolean(), nullable=False),
    sa.Column('first_command_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dashboard_viewed', sa.Boolean(), nullable=False),
    sa.Column('dashboard_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teammate_invited', sa.Boolean(), nullable=False),
    sa.Column('teammate_invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_onboarding_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teams_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False, comment='Teams channel ID from Bot Framework activity'),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('service_url', sa.String(length=512), nullable=False, comment='Bot Connector Service URL for this Teams region'),
    sa.Column('conversation_id', sa.String(length=512), nullable=False, comment='Conversation ID for sending proactive messages'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_teams_channel_workspace'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_channels_workspace_id'), 'teams_channels', ['workspace_id'], unique=False)
    op.create_table('workspace_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('keyword_rules', sa.JSON(), nullable=True),
    sa.Column('high_priority_channels', sa.JSON(), nullable=True),
    sa.Column('drift_alert_hours', sa.Integer(), nullable=False),
    sa.Column('owner_slack_id', sa.String(length=64), nullable=True),
    sa.Column('integration_config', sa.JSON(), nullable=True, comment='Stores integration credentials: Notion / Jira / Trello'),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('default_timezone', sa.String(length=64), nullable=True),
    sa.Column('default_currency', sa.String(length=8), nullable=True),
    sa.Column('teams_tenant_id', sa.String(length=128), nullable=True, comment='Azure AD tenant ID — links workspace to a Teams organisation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_ws_settings_workspace'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.add_column('tasks', sa.Column('title', sa.String(length=500), server_default='Untitled task', nullable=False))
    op.add_column('tasks', sa.Column('assignee_id', sa.String(length=64), nullable=True))
    op.add_column('tasks', sa.Column('share_token', sa.String(length=32), nullable=True))
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('pinged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('owner_pinged_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'task_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tasks', 'source_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('ix_tasks_assignee', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_status_created_at', table_name='tasks')
    op.create_index('ix_tasks_owner_id', 'tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tasks_share_token'), 'tasks', ['share_token'], unique=True)
    op.create_index('ix_tasks_workspace_id', 'tasks', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_task_owner', 'tasks', 'users', ['owner_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_task_workspace', 'tasks', 'workspaces', ['workspace_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_task_workspace', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_task_owner', 'tasks', type_='foreignkey')
    op.drop_index('ix_tasks_workspace_id', table_name='tasks')
    op.drop_index(op.f('ix_tasks_share_token'), table_name='tasks')
    op.drop_index('ix_tasks_owner_id', table_name='tasks')
    op.create_index('ix_tasks_status_created_at', 'tasks', ['status', 'created_at'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_assignee', 'tasks', ['assignee'], unique=False)
    op.alter_column('tasks', 'source_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tasks', 'task_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('tasks', 'owner_pinged_at')
    op.drop_column('tasks', 'pinged_at')
    op.drop_column('tasks', 'workspace_id')
    op.drop_column('tasks', 'owner_id')
    op.drop_column('tasks', 'share_token')
    op.drop_column('tasks', 'assignee_id')
    op.drop_column('tasks', 'title')
    op.drop_table('workspace_settings')
    op.drop_index(op.f('ix_teams_channels_workspace_id'), table_name='teams_channels')
    op.drop_table('teams_channels')
    op.drop_table('onboarding_progress')
    op.drop_index('ix_feedback_user_id', table_name='feedback')
    op.drop_index('ix_feedback_type', table_name='feedback')
    op.drop_index('ix_feedback_status', table_name='feedback')
    op.drop_table('feedback')
    # feedback's 'type' and 'status' columns used plain sa.Enum (create_type
    # defaults to True), so drop_table does not clean up the Postgres types —
    # remove them explicitly or a later re-upgrade hits "type already exists".
    op.execute("DROP TYPE IF EXISTS feedbacktype_enum")
    op.execute("DROP TYPE IF EXISTS feedbackstatus_enum")
    op.drop_index('ix_api_keys_workspace_id', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_referred_by_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # same issue as above — users.role is userrole_enum, created with the
    # SQLAlchemy default create_type=True, so it survives drop_table('users').
    op.execute("DROP TYPE IF EXISTS userrole_enum")
    op.drop_index(op.f('ix_freelancers_referral_code'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_email'), table_name='freelancers')
    op.drop_table('freelancers')
    op.drop_index(op.f('ix_freelancer_requests_email'), table_name='freelancer_requests')
    op.drop_table('freelancer_requests')
    # ### end Alembic commands ###
